### ISSUE TITLE
Example app does not load

### ISSUE THREAD

**Issue by bpedazur** [Glartek/flutter-unity#1]
The demo app crashes when opening, not even getting to the first page.

**Comment by marcotuna** [comment]
Hello @bpedazur. Can you provide further details?
Are you trying to run this on the emulator? If so, please note that with this plugin it is not possible to use the emulator on your pc because you are probably running on x86, this plugin only runs on ARMv7 or ARM64. It is specified on the example instructions from the README

**Comment by bpedazur** [comment]
Hi @marcotuna, thank you for your reply. The app can not be opened on my physical devices. Unfortunately, I don't have any further details as the app crashes immediately.

**Comment by bpedazur** [comment]
Hey,

Starting from scratch, rewriting main.dart and rebuilding the Unity project seems to solve the problem.

**Comment by marcotuna** [comment]
Great, about the problem you reported initially, if you have further details such as logs from adb, it would be great to see where's the problem origin, otherwise I might close this issue since you were able to run the project from stratch.
