### ISSUE TITLE
References to platform views lost in iOS due to gViews being reinitialised

### ISSUE THREAD

**Issue by jamesncl** [Glartek/flutter-unity#18]
I've been having problems where messages from Unity to iOS stop being received. This seems to happen if I have multiple UnityView widgets on the flutter side, and I navigate between them. I've done some digging and found a problem - the following function [in FlutterUnityPlugin.m](https://github.com/Glartek/flutter-unity/blob/master/ios/Classes/FlutterUnityPlugin.m) is called multiple times:

```
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
    UfwLoad();
    gViews = [[NSMutableArray alloc] init];
    FlutterUnityViewFactory * viewFactory = [[FlutterUnityViewFactory alloc] initWithMessenger: [registrar messenger]];
    [registrar registerViewFactory: viewFactory withId: @"unity_view"];
} 
```

This means that when this function is called the second or subsequent times, the `gView` variable is reinitialised, and so any references to views created by the viewfactory are lost. I think this is why my messages suddenly step being received by flutter - Unity is passing messages to iOS, but iOS no longer sends them to the UnityView in flutter because it doesn't have references to the views. Specifically, when it goes around this loop:

```
 for (FlutterUnityView * view in gViews) {
            if ((int64_t)messageId < 0 || (int64_t)messageId == [view viewId]) {
                [view onMessage: messageData];
            }
        }
``` 

It does not find all the views. I suspect this is also the cause of [this possibly related issue](https://github.com/Glartek/flutter-unity/issues/14).

I would suggest that a check is added to only initialise `gViews` if it is 'nil'?

**Comment by ericloureiro** [comment]
Hello @jamesncl, 

As I can see you have been working on iOS a lot more than our team has.
Our focus has been majority on Android environment. 

I would like to suggest you to send a Pull Request with this validation.

**Comment by cookiejarlid** [comment]
Hi @jamesncl,

According to the [docs](https://api.flutter.dev/objcdoc/Protocols/FlutterPlugin.html#/c:objc(pl)FlutterPlugin(cm)registerWithRegistrar:), it doesn't make sense to me that `registerWithRegistrar` could be called multiple times unless there's something wrong with your plugin registrant.
Because of this, the plugin shouldn't need to check if it's already been initialized.
Since no one else has reported this, I'll assume something was wrong on your end and I'll close the issue. If that's not the case and there's any information on why `registerWithRegistrar` is being called multiple times, please reopen it.
