### ISSUE TITLE
onReattached is undocumented, when does it trigger?

### ISSUE THREAD

**Issue by timbotimbo** [Glartek/flutter-unity#28]
The UnityView has functions for 3 events/callbacks.
```
UnityView(
            onCreated: onUnityViewCreated,
            onReattached: onUnityViewReattached,
            onMessage: onUnityViewMessage,
            // key: 
          )
``` 
How or when is `onReattached` triggered? 
I can't find it in either the example project or the Readme.

Running the example project on Android: 
Every time you click the "test" button and enter the UnityViewPage, it will trigger `onCreated`.
The same happens on a second click when the unity loading screen doesn't show up.

`unityViewController.pause()` or `unityViewController.resume()` don't trigger it either.

Giving the UnityView a `key:valueKey(..)` and removing/adding the widget doesn't seem to change anything either.

**Comment by cookiejarlid** [comment]
Hi @timbotimbo,

The plugin can only have a single Unity player running, but it can have any number of views. When you create a view, the player is automatically attached to that view and detached from the view it was previously attached to. It can also be reattached to a view if you send commands to that view or if the current view it is attached to is destroyed.

Let's say you create 3 `UnityView`'s (view1, view2 and view3). Since the player can only be attached to a single view at any given time, it will in the end be attached to the last view you created, which is view3. If you then destroy view3, the player will be attached to view2 and view2's `onReattached` will be called. If you then send a command to view1, the player will be attached to view1 and view1's `onReattached` will be called. And if you then destroy view1, the player will be attached to view2 and view2's `onReattached` will be called.

I hope that was clear.

**Comment by timbotimbo** [comment]
Thanks for the quick and clear explanation.
After trying it, it works like you explained.
