### ISSUE TITLE
Restart unity player

### ISSUE THREAD

**Issue by dogganidhal** [Glartek/flutter-unity#3]
Hello there,

I would like to restart the unity player each time the widget UnityView is rendered,  a simple example would be :

* I navigate into a widget with UnityView
* Play a game
* Navigate out of the widget with UnityView
* Come back later to the widget with UnityView and have a fresh start

Current behaviour : when the UnityView is recreated, the game is at the last state it was in.
Am I missing something ?

Thanks in advance.

**Comment by cookiejarlid** [comment]
That is the expected behavior. As far as I can tell from both Android and iOS Unity libraries, there doesn't seem to be a way to reload the Unity application that's running on a player. You can still achieve what you're trying to do by instructing your Unity application (by sending a message in the `onCreated` callback of your `UnityView` widget) to go back to its initial state.

**Comment by dogganidhal** [comment]
Yes, I was thinking about doing something similar, I just wanted to make sure that there is no better way to do it.

Thanks anyway.

Wonderful job BTW 🙏🏼
